using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LIMSApi.Models
{
    /// <summary>
    /// EnvironmentDailyRecord: Daily temperature/humidity reading for a lab room.
    /// Child of NablEnvironmentMonitoring (monthly header → daily records).
    /// Auto-generated by Hangfire job, editable by user.
    /// </summary>
    public class EnvironmentDailyRecord : AuditProperty
    {
        [Key]
        public long ID { get; set; }

        public long EnvironmentMonitoringID { get; set; }

        public DateTime RecordDate { get; set; }

        [Column(TypeName = "decimal(6,2)")]
        public decimal? Temperature { get; set; }

        [Column(TypeName = "decimal(6,2)")]
        public decimal? Humidity { get; set; }

        [Column(TypeName = "decimal(6,2)")]
        public decimal? Pressure { get; set; }

        [MaxLength(100)]
        public string? AirQuality { get; set; }

        [MaxLength(50)]
        public string? ObservedTime { get; set; }

        [MaxLength(200)]
        public string? ObservedBy { get; set; }

        public bool IsWithinLimits { get; set; } = true;

        [MaxLength(500)]
        public string? Remarks { get; set; }

        [ForeignKey(nameof(EnvironmentMonitoringID))]
        public virtual NablEnvironmentMonitoring? EnvironmentMonitoring { get; set; }
    }
}
