using System.Net;
using System.Text.Json;
using LIMSApi.IntegrationTests.Helpers;
using LIMSApi.IntegrationTests.Infrastructure;

namespace LIMSApi.IntegrationTests.Tests;

[Collection(TestConstants.ApiTestCollection)]
[TestCaseOrderer("LIMSApi.IntegrationTests.Infrastructure.AlphabeticalOrderer",
    "LIMSApi.IntegrationTests")]
public class T03_SampleInwardTests : ApiTestBase
{
    private const string BaseUrl = "/api/SampleInward";
    private static long _inwardId;

    public T03_SampleInwardTests(AuthFixture fixture) : base(fixture) { }

    [Fact]
    public async Task Step01_List_ReturnsPagedResponse()
    {
        var (status, body) = await PostListAsync($"{BaseUrl}/list");
        AssertOk(status);
        AssertPagedResponse(body);
    }

    [Fact]
    public async Task Step02_PlanList_ReturnsPagedResponse()
    {
        var (status, body) = await PostListAsync($"{BaseUrl}/plan-list");
        AssertOk(status);
        AssertPagedResponse(body);
    }

    [Fact]
    public async Task Step03_ReviewList_ReturnsPagedResponse()
    {
        var (status, body) = await PostListAsync($"{BaseUrl}/review-list");
        AssertOk(status);
        AssertPagedResponse(body);
    }

    [Fact]
    public async Task Step04_CaseNumber_ReturnsAutoGenerated()
    {
        var (status, body) = await GetAsync($"{BaseUrl}/case-number");
        AssertOk(status);
        AssertNotEmpty(body);
    }

    [Fact]
    public async Task Step05_Dropdown_ReturnsData()
    {
        var (status, _) = await GetDropdownAsync($"{BaseUrl}/dropdown");
        AssertOk(status);
    }

    [Fact]
    public async Task Step06_PreparationInwardDropdown_ReturnsData()
    {
        var (status, _) = await GetDropdownAsync($"{BaseUrl}/preparation-inward-dropdown");
        AssertOk(status);
    }

    [Fact]
    public async Task Step07_List_WithSearch_ReturnsFiltered()
    {
        var filter = new PageFilterBuilder()
            .Page(1, 5)
            .SortBy("ID", "desc")
            .Build();

        var (status, body) = await PostAsync($"{BaseUrl}/list", filter);
        AssertOk(status);
        AssertPagedResponse(body);
    }

    [Fact]
    public async Task Step08_List_WithIdSort_ReturnsData()
    {
        var filter = new PageFilterBuilder()
            .Page(1, 10)
            .SortBy("ID", "desc")
            .Build();

        var (status, body) = await PostAsync($"{BaseUrl}/list", filter);
        AssertOk(status);
        AssertPagedResponse(body);
    }

    [Fact]
    public async Task Step09_Details_GetFirstInward()
    {
        // Get the first inward from list to use for detail tests
        var (listStatus, listBody) = await PostListAsync($"{BaseUrl}/list", pageSize: 1);
        AssertOk(listStatus);

        var data = listBody.GetProperty("items");
        if (data.GetArrayLength() > 0)
        {
            _inwardId = data[0].GetProperty("id").GetInt64();

            var (status, body) = await GetAsync($"{BaseUrl}/details/{_inwardId}");
            AssertOk(status);
            AssertNotEmpty(body);
        }
    }

    [Fact]
    public async Task Step10_DetailsWithPlan_ReturnsData()
    {
        if (_inwardId == 0) return;

        var (status, body) = await GetAsync($"{BaseUrl}/details-with-plan/{_inwardId}");
        AssertOk(status);
        AssertNotEmpty(body);
    }

    [Fact]
    public async Task Step11_Details_NonExistentId_ReturnsNoContent()
    {
        var (status, _) = await GetAsync($"{BaseUrl}/details/{TestConstants.NonExistentId}");
        Assert.True(status == HttpStatusCode.NoContent || status == HttpStatusCode.NotFound || status == HttpStatusCode.BadRequest);
    }

    [Fact]
    public async Task Step12_List_Pagination_Page1And2_Different()
    {
        var (status1, body1) = await PostListAsync($"{BaseUrl}/list", pageNumber: 1, pageSize: 2);
        var (status2, body2) = await PostListAsync($"{BaseUrl}/list", pageNumber: 2, pageSize: 2);

        AssertOk(status1);
        AssertOk(status2);

        // Both should be valid paged responses
        AssertPagedResponse(body1);
        AssertPagedResponse(body2);
    }

    [Fact]
    public async Task Step13_List_WithoutAuth_Returns401()
    {
        var status = await PostUnauthAsync($"{BaseUrl}/list", TestDataFactory.DefaultPageFilter());
        AssertUnauthorized(status);
    }

    [Fact]
    public async Task Step14_Details_WithoutAuth_Returns401()
    {
        var status = await GetUnauthAsync($"{BaseUrl}/details/1");
        AssertUnauthorized(status);
    }
}
